# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AVcuMWvGKSrYdkRElxi4d7pxIxmWTj_I
"""

print ("girimon")